### ISSUE TITLE
If config specified non-existent emoji, status will not change 

### ISSUE THREAD

**Issue by Silmarill** [nikialeksey/meerk#3]
Steps to reproduse:

1. Specify non-existent emoji in config like `:great_emoji_72_from_pack_123:`
2. Launch bot

Result: Emoji in the slack will not change
Expected: Changing status without changing emoji

**Comment by nikialeksey** [comment]
@Silmarill There will be readable exception, when incorrect emoji appears in config, something like this:
`meerk.status.SyncException.SyncException: Can not sync slack status, because profile_status_set_failed_not_valid_emoji`.
