### ISSUE TITLE
Readme Issues

### ISSUE THREAD

**Issue by Silmarill** [nikialeksey/meerk#5]
Please write a couple of lines about most popular calendars and FAQ with possible errors.
1. Google Calendar is only used by iCal (so make public on **top** and get direct link on .iCal-file at **bottom** of Settings)
2. If [this ](https://i.imgur.com/AfTfshs.png) is the error, then you probably have 2 pythons installed on PC.
3. Required pyton version - 2.7

**Comment by nikialeksey** [comment]
1. Added info about google calendar specifics
2. I think it does not related with current project
3. There is badge in readme, but I add text about python 2.7 in **"How to run"** section

Thanks!
